
#### async和await关键字

1. **作用**
   1) 简化创建promise对象的书写
      1. 不用在then、then的链式调用，看起来不是很方便
   2) 是一个语法糖


2. **使用**
   1) `await`的使用，必须在`async`的环境下
      1) `async`的使用可以没有`await`
      2) `await`的使用必须存在`async`


3. **async的使用以及原理**
   1) 作用
      1) 创建一个promise对象
   2) 使用
      1) 该关键字加在函数的前面，即function的前面
      2) 对应的函数就变成了promise对象的创建函数
      3) 如果对应的函数在执行时报错，则该函数创建的promise对象的状态变为`rejected`
      4) 默认触发成功状态，函数的返回值，作为触发成功状态时的传参
      5) **被标记的函数中的代码是同步执行的，并不是异步执行**
         1) 等价于Promise传参函数中的函数体，是立即执行的
   3) 示范代码
   ```js
   async function a() {
       console.log(123);
       return 1;
   }
   // 相当于
   function a() {
       return new Promise( (resolve, reject) => {
           console.log(123);
           resolve(1);
       } )
   }
   ```


4. **await的使用以及原理**
   1) 作用
      1) 进行异步管理
   2) 使用
      1) **await也是一个标记，并且存在于被async标记的函数中**
      2) **await后面的代码就是异步执行的**
      3) await标记一个表达式，表达式的运算结果返回
         1) 即 `const a = await ?;`
         2) a接收到的就是await后面表达式的返回值
      4) await后面跟一个普通的表达式，则下面的代码直接执行(异步执行)
      5) await后面跟一个promise对象，则下方的代码执行，受promise对象的状态控制
         1) 当状态变为resolved时，下方的代码才继续执行
   3) 原理
      1) **await下方的代码是放在then中的成功回调函数中，作为函数体存在**
      2) **函数的执行受await后面的promise对象的状态控制**
      3) 如果后面是一个普通的表达式，则自动创建一个promise对象
         1) 默认触发成功状态，表达式的值，作为触发成功状态的传参
         2) 报错，触发async绑定函数创建的promise对象的失败状态
         3) 可以使用try-catch捕获错误，进行处理
            1) 只有成功回调函数，如果报错，没有失败回调函数，await处就会报错
            2) try-catch就可以进行错误的捕获
            3) 如果没有进行捕获，则相当于async绑定函数报错，触发promise对象的失败状态
      4) await后面的promise对象的状态变为成功状态后，状态传入值，传入回调函数中
         1) 即声明的接收await返回数据的变量
   4) 注意点
      1) async绑定的函数，创建的promise对象的状态，受函数执行的返回值的控制
      2) 由于await会阻止代码的执行，所以return的执行也会被阻止，还没有解析
      3) 此时创建的promise对象的状态是改变不了的
      4) 只有，所有的await处理完成，才解析到return，改变创建的promise对象的状态
         1) 此时创建的promise对象上绑定的回调函数才进行执行
         2) 即创建的promise对象上绑定的回调函数最后执行 
      5) await虽然造成阻塞的现象，其实是把代码放在了then中进行注册
         1) 然后等待await后面的promise对象状态的改变
         2) **实际上执行栈中的代码执行是没有阻塞的**




